services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: academix_sqlserver
    environment:
      SA_PASSWORD: "Academix@K64"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - academix_network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: academix_backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=AcademixDB;User Id=sa;Password=Academix@K64;TrustServerCertificate=true;
    ports:
      - "5000:5000"
    depends_on:
      - sqlserver
    networks:
      - academix_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: academix_frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - academix_network
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: academix_adminer
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    networks:
      - academix_network

volumes:
  sql_data:

networks:
  academix_network:
    driver: bridge
